version: '3'

networks:
  laravel:

services:
  nginx:
    depends_on:
      - mysql
      - php
    image: nginx:1.20.1-alpine
    container_name: webserver
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    restart: "unless-stopped"
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: menus
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    ports:
      - "9000:9000"
    networks:
      - laravel
